In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

In [69]:
train = pd.read_csv("train_data.csv")

In [70]:
train.head()

name   brand  \
0  All-New Fire HD 8 Tablet, 8" HD Display, Wi-Fi...  Amazon   
1        Amazon - Echo Plus w/ Built-In Hub - Silver  Amazon   
2  Amazon Echo Show Alexa-enabled Bluetooth Speak...  Amazon   
3  Fire HD 10 Tablet, 10.1 HD Display, Wi-Fi, 16 ...  Amazon   
4  Brand New Amazon Kindle Fire 16gb 7" Ips Displ...  Amazon   

                                          categories  \
0  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
1  Amazon Echo,Smart Home,Networking,Home & Tools...   
2  Amazon Echo,Virtual Assistant Speakers,Electro...   
3  eBook Readers,Fire Tablets,Electronics Feature...   
4  Computers/Tablets & Networking,Tablets & eBook...   

             primaryCategories              reviews.date  \
0                  Electronics  2016-12-26T00:00:00.000Z   
1         Electronics,Hardware  2018-01-17T00:00:00.000Z   
2         Electronics,Hardware  2017-12-20T00:00:00.000Z   
3  Office Supplies,Electronics  2017-08-04T00:00:00.000Z   
4                  Electronics  2017-01-23T00:00:00.000Z   

                                        reviews.text  \
0  Purchased on Black FridayPros - Great Price (e...   
1  I purchased two Amazon in Echo Plus and two do...   
2  Just an average Alexa option. Does show a few ...   
3  very good product. Exactly what I wanted, and ...   
4  This is the 3rd one I've purchased. I've bough...   

              reviews.title sentiment  
0           Powerful tablet  Positive  
1  Amazon Echo Plus AWESOME  Positive  
2                   Average   Neutral  
3               Greattttttt  Positive  
4             Very durable!  Positive

In [71]:
test_hid = pd.read_csv("test_data_hidden.csv")

In [72]:
test_hid.head()

name   brand  \
0  Fire Tablet, 7 Display, Wi-Fi, 16 GB - Include...  Amazon   
1  Amazon Echo Show Alexa-enabled Bluetooth Speak...  Amazon   
2  All-New Fire HD 8 Tablet, 8" HD Display, Wi-Fi...  Amazon   
3  Brand New Amazon Kindle Fire 16gb 7" Ips Displ...  Amazon   
4  Amazon Echo Show Alexa-enabled Bluetooth Speak...  Amazon   

                                          categories     primaryCategories  \
0  Fire Tablets,Computers/Tablets & Networking,Ta...           Electronics   
1  Computers,Amazon Echo,Virtual Assistant Speake...  Electronics,Hardware   
2  Electronics,iPad & Tablets,All Tablets,Fire Ta...           Electronics   
3  Computers/Tablets & Networking,Tablets & eBook...           Electronics   
4  Computers,Amazon Echo,Virtual Assistant Speake...  Electronics,Hardware   

               reviews.date  \
0  2016-05-23T00:00:00.000Z   
1  2018-01-02T00:00:00.000Z   
2  2017-01-02T00:00:00.000Z   
3  2017-03-25T00:00:00.000Z   
4  2017-11-15T00:00:00.000Z   

                                        reviews.text  \
0  Amazon kindle fire has a lot of free app and c...   
1  The Echo Show is a great addition to the Amazo...   
2  Great value from Best Buy. Bought at Christmas...   
3  I use mine for email, Facebook ,games and to g...   
4  This is a fantastic item & the person I bought...   

                       reviews.title sentiment  
0                  very handy device  Positive  
1         Another winner from Amazon  Positive  
2  simple to use and reliable so far  Positive  
3                         Love it!!!  Positive  
4                         Fantastic!  Positive

In [73]:
test = pd.read_csv("test_data.csv")

In [74]:
test.head()

name   brand  \
0  Fire Tablet, 7 Display, Wi-Fi, 16 GB - Include...  Amazon   
1  Amazon Echo Show Alexa-enabled Bluetooth Speak...  Amazon   
2  All-New Fire HD 8 Tablet, 8" HD Display, Wi-Fi...  Amazon   
3  Brand New Amazon Kindle Fire 16gb 7" Ips Displ...  Amazon   
4  Amazon Echo Show Alexa-enabled Bluetooth Speak...  Amazon   

                                          categories     primaryCategories  \
0  Fire Tablets,Computers/Tablets & Networking,Ta...           Electronics   
1  Computers,Amazon Echo,Virtual Assistant Speake...  Electronics,Hardware   
2  Electronics,iPad & Tablets,All Tablets,Fire Ta...           Electronics   
3  Computers/Tablets & Networking,Tablets & eBook...           Electronics   
4  Computers,Amazon Echo,Virtual Assistant Speake...  Electronics,Hardware   

               reviews.date  \
0  2016-05-23T00:00:00.000Z   
1  2018-01-02T00:00:00.000Z   
2  2017-01-02T00:00:00.000Z   
3  2017-03-25T00:00:00.000Z   
4  2017-11-15T00:00:00.000Z   

                                        reviews.text  \
0  Amazon kindle fire has a lot of free app and c...   
1  The Echo Show is a great addition to the Amazo...   
2  Great value from Best Buy. Bought at Christmas...   
3  I use mine for email, Facebook ,games and to g...   
4  This is a fantastic item & the person I bought...   

                       reviews.title  
0                  very handy device  
1         Another winner from Amazon  
2  simple to use and reliable so far  
3                         Love it!!!  
4                         Fantastic!

In [75]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   name               4000 non-null   object
 1   brand              4000 non-null   object
 2   categories         4000 non-null   object
 3   primaryCategories  4000 non-null   object
 4   reviews.date       4000 non-null   object
 5   reviews.text       4000 non-null   object
 6   reviews.title      3990 non-null   object
 7   sentiment          4000 non-null   object
dtypes: object(8)
memory usage: 250.1+ KB


In [76]:
test_hid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   name               1000 non-null   object
 1   brand              1000 non-null   object
 2   categories         1000 non-null   object
 3   primaryCategories  1000 non-null   object
 4   reviews.date       1000 non-null   object
 5   reviews.text       1000 non-null   object
 6   reviews.title      997 non-null    object
 7   sentiment          1000 non-null   object
dtypes: object(8)
memory usage: 62.6+ KB


In [77]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   name               1000 non-null   object
 1   brand              1000 non-null   object
 2   categories         1000 non-null   object
 3   primaryCategories  1000 non-null   object
 4   reviews.date       1000 non-null   object
 5   reviews.text       1000 non-null   object
 6   reviews.title      997 non-null    object
dtypes: object(7)
memory usage: 54.8+ KB


In [78]:
train[train.sentiment=='Positive'][['reviews.text','reviews.title']].head(10)

reviews.text  \
0   Purchased on Black FridayPros - Great Price (e...   
1   I purchased two Amazon in Echo Plus and two do...   
3   very good product. Exactly what I wanted, and ...   
4   This is the 3rd one I've purchased. I've bough...   
5   This is a great product. Light weight. I wish ...   
7   Purchased this for my son. Has room to upgrade...   
8   Bought this for my mom and it was just what sh...   
10  I got this tablet to replace my sons old one, ...   
11  Great product for the kids gaming apps parenta...   
12  Love the choice of colors. Have two kindles of...   

                             reviews.title  
0                          Powerful tablet  
1                 Amazon Echo Plus AWESOME  
3                              Greattttttt  
4                            Very durable!  
5                         You will love it  
7          Great for kids or smaller needs  
8                             Great tablet  
10                            Great Tablet  
11                             Works great  
12  great pad for both children and adults

In [79]:
train[train.sentiment=='Neutral'][['reviews.text','reviews.title']].head(10)

reviews.text  \
2    Just an average Alexa option. Does show a few ...   
6    My 7-year old daughter saved up to by this. He...   
17   Not as good as before the old kindle, just sea...   
59   There is nothing spectacular about this item b...   
95   It's unfair for me to rate this product cause ...   
114  I bought this as s present for my 65 year old ...   
146  Bought this tablet for 8 year old. It holding ...   
147  bought a few kindles in the past but this time...   
148  Not a substitute for an iPad, but a really goo...   
187  This device is a good if you are looking for a...   

                                  reviews.title  
2                                       Average  
6                     OK For Entry Level Tablet  
17                        Not as good as before  
59   Does what it says, missing one key feature  
95                        Haven't set it up yet  
114                                Solid tablet  
146                                 Fire tablet  
147                              Came defective  
148                                 Good Reader  
187                         Good for 4 year old

In [80]:

train[train.sentiment=='Negative'][['reviews.text','reviews.title']].head(10)

reviews.text  \
9    was cheap, can not run chrome stuff, returned ...   
97   Worthless, except as a regular echo and a poor...   
104  Too bad Amazon turned this tablet into a big a...   
121  I bought this Kindle for my 7 year old grand-d...   
150  I am reading positive reviews and wish I could...   
151  I have to say it was a little confusing and fr...   
249  It's a good device for children because they d...   
267  the speaker voice quality is terrible compare ...   
368  Needs to be a stand alone device. I should hav...   
530  Has a very good Bluetooth speakers sound quali...   

                                      reviews.title  
9     was cheap, can not run chrome stuff, returned  
97                Useless screen so why pay for it?  
104                            Amazon Fire 7 Tablet  
121                                    Kid's Kindle  
150  Have never purchased a more frustrating Device  
151                                     not big fan  
249                                   Good for kids  
267              terrible product,bad voice quality  
368                Needs to be a stand alone device  
530                          Good Bluetooth speaker

In [81]:
train["text"] = train["reviews.text"].str.cat(train["reviews.title"], sep=" ")

In [82]:
train = train[['text','sentiment']]
train.dropna(inplace=True)


In [83]:
from sklearn.feature_extraction import text
my_stop_words = text.ENGLISH_STOP_WORDS
#Printing first few stop words
print("Few stop words: ", list(my_stop_words)[0:10])

Few stop words:  ['cant', 'never', 'whenever', 'along', 'mill', 'except', 'seems', 'noone', 'can', 'amoungst']


In [84]:
# Adding custom words to the list of stop words
my_stop_words = text.ENGLISH_STOP_WORDS.union( ['Amazon', 'tablet', 'echo', 'inch', 'bluetooth', 'alexa', 'purchase', 'product',
                                               'kindle', 'bought', 'prime', 'music', '7', 'speaker'])

In [85]:
# Setting stop words list
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(stop_words = my_stop_words,max_features=1000)
feature_vector = count_vectorizer.fit(train.text)
train_features = count_vectorizer.transform(train.text)
features = feature_vector.get_feature_names()
features_counts = np.sum(train_features.toarray(), axis=0)
feature_counts = pd.DataFrame( dict( features = features,
counts = features_counts ) )

Data Cleaning - Stemming or Lemmatization

In [86]:
from nltk.stem.snowball import PorterStemmer
stemmer = PorterStemmer()
analyzer = CountVectorizer().build_analyzer()



#Custom function for stemming and stop word removal
def stemmed_words(doc):
    ### Stemming of words
    stemmed_words = (stemmer.stem(w) for w in analyzer(doc))
    ### Remove the words in stop words list
    non_stop_words = [ word for word in list(set(stemmed_words) - set(my_stop_words)) ]
    return non_stop_words

In [87]:
count_vectorizer = CountVectorizer( analyzer=stemmed_words,
max_features = 1000)
feature_vector = count_vectorizer.fit( train.text )
train_features = count_vectorizer.transform( train.text )
features = feature_vector.get_feature_names()
features_counts = np.sum( train_features.toarray(), axis = 0 )
feature_counts = pd.DataFrame( dict( features = features,
counts = features_counts ) )
feature_counts.sort_values( "counts", ascending = False )[0:15]

features  counts
407    great    1995
896      thi    1663
546     love    1396
937      use    1105
394     good     693
277     easi     687
953       wa     629
944     veri     615
50    amazon     569
496    kindl     537
979     work     515
493      kid     513
522     like     473
695    price     469
721     read     447

In [88]:
import nltk
from nltk.stem import PorterStemmer
# library for regular expressions
import re
stemmer = PorterStemmer()

In [89]:
def get_stemmed_tokens( doc ):
    # Tokenize the documents to words
    all_tokens = [word for word in nltk.word_tokenize(doc)]
    clean_tokens = []
    # remove the all characters other than alphabets. It takes a regex for matching.
    for each_token in all_tokens:
        if re.search('[a-zA-Z]', each_token):
            clean_tokens.append(each_token)
    
    
    # Stem the words
    stemmed_tokens = [stemmer.stem(t) for t in clean_tokens]
    return stemmed_tokens

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer( analyzer=stemmed_words,max_features = 1000)


feature_vector = tfidf_vectorizer.fit( train.text )
train_features = tfidf_vectorizer.transform( train.text )
features = feature_vector.get_feature_names()

In [91]:
# Convert the document vector matrix into dataframe
train_df = pd.DataFrame(train_features.todense())
# Assign the features names to the column
train_df.columns = features
# Assign the sentiment labels to the train_ds
train_df['sentiment'] = train.sentiment
train_df

10  100   11   12   14        15   16  16gb  1st   20  ...  younger  \
0     0.0  0.0  0.0  0.0  0.0  0.305376  0.0   0.0  0.0  0.0  ...      0.0   
1     0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
2     0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
3     0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
4     0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
...   ...  ...  ...  ...  ...       ...  ...   ...  ...  ...  ...      ...   
3985  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
3986  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
3987  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
3988  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   
3989  0.0  0.0  0.0  0.0  0.0  0.000000  0.0   0.0  0.0  0.0  ...      0.0   

      youngest  youtub   yr        äô       äôm  äôt  äôve   äù  sentiment  
0          0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0   Positive  
1          0.0     0.0  0.0  0.150660  0.179918  0.0   0.0  0.0   Positive  
2          0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0    Neutral  
3          0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0   Positive  
4          0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0   Positive  
...        ...     ...  ...       ...       ...  ...   ...  ...        ...  
3985       0.0     0.0  0.0  0.436342  0.000000  0.0   0.0  0.0   Positive  
3986       0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0   Positive  
3987       0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0   Positive  
3988       0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0   Positive  
3989       0.0     0.0  0.0  0.000000  0.000000  0.0   0.0  0.0   Positive  

[3990 rows x 1001 columns]

In [92]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(train_features,train.sentiment,test_size=0.3,random_state=42)

MultinomialNB Classifier


In [93]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train.toarray(),y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [94]:
test_predicted = nb.predict(X_test.toarray())

In [95]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,test_predicted))
print( metrics.classification_report( y_test, test_predicted ) )

[[   1    0   20]
 [   0    0   54]
 [   0    0 1122]]
              precision    recall  f1-score   support

    Negative       1.00      0.05      0.09        21
     Neutral       0.00      0.00      0.00        54
    Positive       0.94      1.00      0.97      1122

    accuracy                           0.94      1197
   macro avg       0.65      0.35      0.35      1197
weighted avg       0.90      0.94      0.91      1197



Logistic Regression

In [96]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train.toarray(),y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [97]:
test_predicted = log_reg.predict(X_test.toarray())

In [98]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,test_predicted))
print( metrics.classification_report( y_test, test_predicted ) )

[[   0    0   21]
 [   0    2   52]
 [   0    0 1122]]
              precision    recall  f1-score   support

    Negative       0.00      0.00      0.00        21
     Neutral       1.00      0.04      0.07        54
    Positive       0.94      1.00      0.97      1122

    accuracy                           0.94      1197
   macro avg       0.65      0.35      0.35      1197
weighted avg       0.93      0.94      0.91      1197



Decision Tree

In [99]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(X_train.toarray(),y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [100]:
tree_predict = tree.predict(X_test.toarray())

In [101]:
from sklearn import metrics
print( metrics.classification_report( y_test, tree_predict ) )

              precision    recall  f1-score   support

    Negative       0.41      0.43      0.42        21
     Neutral       0.24      0.26      0.25        54
    Positive       0.96      0.95      0.96      1122

    accuracy                           0.91      1197
   macro avg       0.53      0.55      0.54      1197
weighted avg       0.92      0.91      0.91      1197



Random Forest

In [102]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10)
rf.fit(X_train.toarray(),y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [103]:
rf_predict = rf.predict(X_test.toarray())

In [104]:
from sklearn import metrics
print( metrics.classification_report( y_test, rf_predict ) )

              precision    recall  f1-score   support

    Negative       0.79      0.52      0.63        21
     Neutral       0.64      0.17      0.26        54
    Positive       0.95      0.99      0.97      1122

    accuracy                           0.95      1197
   macro avg       0.79      0.56      0.62      1197
weighted avg       0.94      0.95      0.94      1197



XGBOOST

In [105]:
from xgboost import XGBClassifier
xgboost = XGBClassifier()
xgboost.fit(X_train.toarray(),y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [106]:
xg_predict = xgboost.predict(X_test.toarray())

In [107]:
print( metrics.classification_report( y_test, xg_predict ) )

              precision    recall  f1-score   support

    Negative       1.00      0.48      0.65        21
     Neutral       0.62      0.19      0.29        54
    Positive       0.95      0.99      0.97      1122

    accuracy                           0.95      1197
   macro avg       0.86      0.55      0.63      1197
weighted avg       0.94      0.95      0.94      1197



SGD - StochasticGradientDescent

In [108]:
from sklearn.linear_model import SGDClassifier
from sklearn.multiclass import OneVsRestClassifier

sgd = OneVsRestClassifier(SGDClassifier())

In [109]:
sgd.fit(X_train.toarray(), y_train)
test_predicted = sgd.predict(X_test.toarray() )
print( metrics.classification_report( y_test, test_predicted ) )

              precision    recall  f1-score   support

    Negative       0.71      0.48      0.57        21
     Neutral       0.48      0.22      0.30        54
    Positive       0.96      0.99      0.97      1122

    accuracy                           0.94      1197
   macro avg       0.72      0.56      0.62      1197
weighted avg       0.93      0.94      0.94      1197



Multi-Class SVM

In [110]:
from sklearn.svm import SVC
svc = SVC(kernel='linear', class_weight='balanced', C=1.0, random_state=0).fit(X_train, y_train) 

In [111]:
svc.fit(X_train.toarray(),y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [112]:
svc_predict = svc.predict(X_test.toarray())

In [113]:
print(metrics.confusion_matrix(y_test, svc_predict))
print( metrics.classification_report( y_test, svc_predict) )

[[  12    4    5]
 [   6   17   31]
 [  14   49 1059]]
              precision    recall  f1-score   support

    Negative       0.38      0.57      0.45        21
     Neutral       0.24      0.31      0.27        54
    Positive       0.97      0.94      0.96      1122

    accuracy                           0.91      1197
   macro avg       0.53      0.61      0.56      1197
weighted avg       0.92      0.91      0.92      1197



ensemble technique using Voting Classifier: XGboost + oversampled_multinomial_NB

In [114]:
from sklearn.ensemble import VotingClassifier
model1 = MultinomialNB()
model2 = XGBClassifier(n_estimator=1000,max_depth=6)
model = VotingClassifier(estimators=[('lr', model1), ('dt', model2)], voting='hard')
model.fit(X_train,y_train)


[10:32:28] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { n_estimator } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




VotingClassifier(estimators=[('lr',
                              MultinomialNB(alpha=1.0, class_prior=None,
                                            fit_prior=True)),
                             ('dt',
                              XGBClassifier(base_score=None, booster=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, gamma=None,
                                            gpu_id=None, importance_type='gain',
                                            interaction_constraints=None,
                                            learning_rate=None,
                                            max_delta_step=None, max_depth=6,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            n_estimator=

In [115]:
y_pred = model.predict(X_test)
y_pred

array(['Positive', 'Positive', 'Positive', ..., 'Positive', 'Positive',
       'Positive'], dtype=object)

In [139]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy :", accuracy_score(y_test,y_pred))

[[   9    0   12]
 [   2   10   42]
 [   0    6 1116]]
              precision    recall  f1-score   support

    Negative       0.82      0.43      0.56        21
     Neutral       0.62      0.19      0.29        54
    Positive       0.95      0.99      0.97      1122

    accuracy                           0.95      1197
   macro avg       0.80      0.54      0.61      1197
weighted avg       0.94      0.95      0.94      1197

Accuracy : 0.948203842940685
